import { 
  FileText, 
  Scissors, 
  Minimize2, 
  Image as ImageIcon, 
  RotateCw, 
  History, 
  LayoutDashboard,
  FileCode,
  FileJson,
  Type,
  Lock,
  Unlock,
  Stamp,
  FileUp,
  FileDown,
  PenTool
} from 'lucide-react';

export const TOOLS = [
  {
    id: 'merge',
    name: 'Merge PDF',
    description: 'Combine multiple PDFs into one document.',
    icon: FileText,
    color: 'bg-red-500',
    path: '/tool/merge',
  },
  {
    id: 'split',
    name: 'Split PDF',
    description: 'Extract pages from your PDF or save each page as a separate PDF.',
    icon: Scissors,
    color: 'bg-blue-500',
    path: '/tool/split',
  },
  {
    id: 'compress',
    name: 'Compress PDF',
    description: 'Reduce file size while optimizing for maximal PDF quality.',
    icon: Minimize2,
    color: 'bg-green-500',
    path: '/tool/compress',
  },
  {
    id: 'pdf-to-word',
    name: 'PDF to Word',
    description: 'Convert your PDF to WORD documents with incredible accuracy.',
    icon: FileText,
    color: 'bg-blue-600',
    path: '/tool/pdf-to-word',
  },
  {
    id: 'pdf-to-powerpoint',
    name: 'PDF to PowerPoint',
    description: 'Convert your PDF to POWERPOINT presentations.',
    icon: FileUp,
    color: 'bg-orange-600',
    path: '/tool/pdf-to-powerpoint',
  },
  {
    id: 'pdf-to-excel',
    name: 'PDF to Excel',
    description: 'Convert your PDF to EXCEL spreadsheets.',
    icon: FileDown,
    color: 'bg-green-600',
    path: '/tool/pdf-to-excel',
  },
  {
    id: 'word-to-pdf',
    name: 'Word to PDF',
    description: 'Convert WORD documents to PDF.',
    icon: FileText,
    color: 'bg-blue-400',
    path: '/tool/word-to-pdf',
  },
  {
    id: 'powerpoint-to-pdf',
    name: 'PowerPoint to PDF',
    description: 'Convert POWERPOINT presentations to PDF.',
    icon: FileUp,
    color: 'bg-orange-400',
    path: '/tool/powerpoint-to-pdf',
  },
  {
    id: 'excel-to-pdf',
    name: 'Excel to PDF',
    description: 'Convert EXCEL spreadsheets to PDF.',
    icon: FileDown,
    color: 'bg-green-400',
    path: '/tool/excel-to-pdf',
  },
  {
    id: 'edit',
    name: 'Edit PDF',
    description: 'Add text, images, shapes or freehand annotations to a PDF.',
    icon: Type,
    color: 'bg-red-400',
    path: '/tool/edit',
  },
  {
    id: 'pdf-to-jpg',
    name: 'PDF to JPG',
    description: 'Extract all images from a PDF or convert each page to a JPG image.',
    icon: ImageIcon,
    color: 'bg-yellow-500',
    path: '/tool/pdf-to-jpg',
  },
  {
    id: 'jpg-to-pdf',
    name: 'JPG to PDF',
    description: 'Convert JPG images to PDF in seconds.',
    icon: ImageIcon,
    color: 'bg-yellow-400',
    path: '/tool/jpg-to-pdf',
  },
  {
    id: 'sign',
    name: 'Sign PDF',
    description: 'Sign yourself or request electronic signatures from others.',
    icon: PenTool,
    color: 'bg-orange-500',
    path: '/tool/sign',
  },
  {
    id: 'watermark',
    name: 'Watermark',
    description: 'Stamp an image or text over your PDF in seconds.',
    icon: Stamp,
    color: 'bg-blue-300',
    path: '/tool/watermark',
  },
  {
    id: 'rotate',
    name: 'Rotate PDF',
    description: 'Rotate your PDFs the way you need them.',
    icon: RotateCw,
    color: 'bg-purple-500',
    path: '/tool/rotate',
  },
  {
    id: 'protect',
    name: 'Protect PDF',
    description: 'Protect PDF files with a password.',
    icon: Lock,
    color: 'bg-slate-900',
    path: '/tool/protect',
  },
];

export const NAV_ITEMS = [
  { name: 'Tools', path: '/', icon: FileText },
  { name: 'Dashboard', path: '/dashboard', icon: LayoutDashboard },
  { name: 'History', path: '/history', icon: History },
];
